[font]
size = 10
normal = { family = "Hack Nerd Font Propo", style = "Regular" }
offset = { x = 1, y = 1}

[general]
import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.local/share/omakub/defaults/alacritty.toml" ]

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
