return {
  'terryma/vim-multiple-cursors',
  'kyazdani42/nvim-web-devicons',
  'kyazdani42/nvim-tree.lua',
  { 'junegunn/fzf', run = './install --bin', },
  'junegunn/fzf.vim',
  'mileszs/ack.vim',
  -- colorscheme
  'joshdick/onedark.vim',
  'morhetz/gruvbox',
  'drewtempelmeyer/palenight.vim',
  'dracula/vim',
  'Yggdroot/indentLine',


  'scrooloose/nerdcommenter',
  'nvim-lua/plenary.nvim',
  'nvim-telescope/telescope.nvim',
  'nvim-lualine/lualine.nvim',
  'Eandrju/cellular-automaton.nvim',
  'nvim-lua/plenary.nvim',
  'nvim-telescope/telescope.nvim',
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-cmdline',
  'hrsh7th/nvim-cmp',
  'hrsh7th/vim-vsnip',
  'SirVer/ultisnips',
  'quangnguyen30192/cmp-nvim-ultisnips',
  'williamboman/mason.nvim',
  'williamboman/mason-lspconfig.nvim',
  'neovim/nvim-lspconfig',
  'shime/vim-livedown',
  'nvim-treesitter/nvim-treesitter',
  'mfussenegger/nvim-dap',
  {
    'phaazon/hop.nvim',
    config = function()
      -- you can configure Hop the way you like here; see :h hop-config
      require 'hop'.setup { keys = 'etovxqpdygfblzhckisuran' }
    end
  },

  'honza/vim-snippets',
  'SirVer/ultisnips',
  'tpope/vim-surround',
  'tpope/vim-rails',
  'tpope/vim-fugitive',
  'godlygeek/tabular',
  'tpope/vim-bundler',
  'jiangmiao/auto-pairs',
  'ngmy/vim-rubocop',
  'jeffkreeftmeijer/vim-numbertoggle',
  'mattn/emmet-vim',
  'editorconfig/editorconfig-vim',
  'airblade/vim-gitgutter',
  'rhysd/git-messenger.vim',
  'tpope/vim-repeat',
  'mxw/vim-jsx',
  'dart-lang/dart-vim-plugin',
  'tpope/vim-endwise',
  'danchoi/ri.vim',
  'ianks/vim-tsx',
'kana/vim-textobj-user',
'wlemuel/vim-tldr',
'Shougo/vimproc.vim',
'Shougo/echodoc.vim',
}
