local state, hop = pcall(require, "hop")
if not state then
  return
end
local directions = require('hop.hint').HintDirection
local keymap = vim.keymap.set
keymap('', 'f', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, { remap = true })
keymap('', 'F', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, { remap = true })
keymap('', 't', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
end, { remap = true })
keymap('', 'T', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
end, { remap = true })
keymap('', ';j', function()
  hop.hint_lines({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR })
end, { remap = true })
keymap('', ';k', function()
  hop.hint_lines({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR })
end, { remap = true })
keymap('', ';b', function()
  hop.hint_words({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR })
end, { remap = true })
keymap('', ';w', function()
  hop.hint_words({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR })
end, { remap = true })
