return {
  'terryma/vim-multiple-cursors',
  'kyazdani42/nvim-web-devicons',
  'kyazdani42/nvim-tree.lua',
  { 'junegunn/fzf',                  build = './install --bin', },
  'junegunn/fzf.vim',
  -- colorscheme
  'joshdick/onedark.vim',
  'morhetz/gruvbox',
  'drewtempelmeyer/palenight.vim',
  'dracula/vim',
  'Yggdroot/indentLine',


  'scrooloose/nerdcommenter',
  'nvim-lualine/lualine.nvim',
  'Eandrju/cellular-automaton.nvim',
  'nvim-lua/plenary.nvim',
  { 'nvim-telescope/telescope.nvim', build = ":TSUpdate",       tag = "0.1.1" },
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-cmdline',
  'hrsh7th/nvim-cmp',
  'hrsh7th/vim-vsnip',
  'SirVer/ultisnips',
  'honza/vim-snippets',
  'quangnguyen30192/cmp-nvim-ultisnips',
  'williamboman/mason.nvim',
  'williamboman/mason-lspconfig.nvim',
  'neovim/nvim-lspconfig',
  "glepnir/lspsaga.nvim",
  'shime/vim-livedown',
  'nvim-treesitter/nvim-treesitter',
  'mfussenegger/nvim-dap',
  {
    'phaazon/hop.nvim',
    config = function()
      -- you can configure Hop the way you like here; see :h hop-config
      require 'hop'.setup { keys = 'etovxqpdygfblzhckisuran' }
    end
  },

  'tpope/vim-surround',
  'tpope/vim-rails',
  'tpope/vim-fugitive',
  'godlygeek/tabular',
  'tpope/vim-bundler',
  'jiangmiao/auto-pairs',
  'ngmy/vim-rubocop',
  'jeffkreeftmeijer/vim-numbertoggle',
  'mattn/emmet-vim',
  'editorconfig/editorconfig-vim',
  'airblade/vim-gitgutter',
  'rhysd/git-messenger.vim',
  'tpope/vim-repeat',
  'mxw/vim-jsx',
  'dart-lang/dart-vim-plugin',
  'tpope/vim-endwise',
  'danchoi/ri.vim',
  'ianks/vim-tsx',
  'kana/vim-textobj-user',
  'wlemuel/vim-tldr',
  'Shougo/vimproc.vim',
  'Shougo/echodoc.vim',
  'github/copilot.vim',
  'shumphrey/fugitive-gitlab.vim',
  -- dadbod
  'tpope/vim-dadbod',
  'kristijanhusak/vim-dadbod-ui',
  'kristijanhusak/vim-dadbod-completion',

  'junegunn/vim-peekaboo',
  'tpope/vim-abolish',
  'kkoomen/vim-doge',
  { 'prettier/vim-prettier', build = 'yarn install --frozen-lockfile --production' },
  'tpope/vim-rhubarb',
  'tpope/vim-sleuth',
  'preservim/vimux',
  'skalnik/vim-vroom',
  'vim-test/vim-test',
  'mhinz/vim-tmuxify',
}
